### ISSUE TITLE
SYNOPSISのコードでUse of uninitialized value in subroutine entryが出る。

### ISSUE THREAD

**Issue by rozary** [tokuhirom/Test-Kantan#7]
``` perl
sub _suite {
    my ($env_key, $tag, $title, $code) = @_;
```

では、引数が4つですが、SYNOPSIS側では3つです。
その為、$titleにCODEが入って$codeがundefになって
｢ Use of uninitialized value in subroutine entry ｣が出ます。

引数は、どの様にするのが正しいのでしょうか?
よろしくおねがいします。

**Comment by tokuhirom** [comment]
おっと｡cb77d97483ba58ccc67afdda4fcbeca6041fe57f で修正していたのですがリリースし忘れてました｡0.37 をリリースしましたー｡
